# Generated by Django 3.2.23 on 2024-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uzless", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorModel",
            fields=[
                ("contractorId", models.AutoField(primary_key=True, serialize=False)),
                ("fullName", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("nip", models.BigIntegerField()),
            ],
        ),
    ]
